// react/column-alignment/src/ColumnAlignment.tsx
import { useRef, useState, useLayoutEffect } from 'react';
import { DataTable } from '@carbon/react';
const {
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableHeader,
  TableRow,
} = DataTable;

import {
  createColumnHelper,
  flexRender,
  getCoreRowModel,
  useReactTable,
} from '@tanstack/react-table';
import { makeData } from './makeData';
import { ExampleLink } from './ExampleLink';
import { Launch } from '@carbon/react/icons';
import * as packageJson from '../package.json';
import { StatusIcon } from '@carbon/ibm-products';

type Resource = {
  id: string;
  name: string;
  rule: string;
  status: string;
  other: string;
  example: string;
};

const columnHelper = createColumnHelper<Resource>();

const getStatusIconValue = (kind) => {
  if (kind === 'disabled') {
    return 'fatal';
  }
  if (kind === 'starting') {
    return 'in-progress';
  }
  if (kind === 'active') {
    return 'running';
  }
  return 'running';
};

const columns = [
  columnHelper.accessor((row) => row.name, {
    id: 'name',
    cell: (info) => <i>{info.getValue()}</i>,
    header: () => <span>Name</span>,
  }),
  columnHelper.accessor('rule', {
    header: () => 'Rule',
    cell: (info) => info.renderValue(),
  }),
  columnHelper.accessor('status', {
    header: () => <span className="center-align-cell">Status</span>,
    cell: (info) => {
      console.log(info.renderValue());
      const iconProps = {
        size: 'sm',
        theme: 'light',
        kind: getStatusIconValue(info.renderValue()),
        iconDescription: info.renderValue(),
      };
      // @ts-expect-error
      return <StatusIcon className="center-align-cell" {...iconProps} />;
    },
  }),
  columnHelper.accessor('other', {
    header: 'Other',
  }),
  columnHelper.accessor('example', {
    header: () => <span className="right-align-cell">Example</span>,
    cell: (info) => (
      <span className="right-align-cell">{info.renderValue()}</span>
    ),
  }),
];

export const ColumnAlignment = () => {
  const [data] = useState(makeData(7));

  const table = useReactTable({
    data,
    columns,
    getCoreRowModel: getCoreRowModel(),
  });

  const tableWrap = useRef<HTMLDivElement>();

  useLayoutEffect(() => {
    const tableWrapElement = tableWrap.current;
    if (tableWrapElement) {
      const tableElement = tableWrapElement.querySelector('table');
      tableElement.style.width = `${table.getCenterTotalSize()}px`;
    }
  }, [table]);

  return (
    <TableContainer
      title="Column alignment"
      className="basic-table tanstack-example"
      description={
        <span className="flex">
          <ExampleLink
            url={`${import.meta.env.VITE_CODE_SANDBOX_URL_ROOT}/${
              packageJson.name
            }`}
            icon={Launch}
            label="Code sandbox"
          />
          <ExampleLink
            url={`${import.meta.env.VITE_STACK_BLITZ_URL_ROOT}/${
              packageJson.name
            }`}
            icon={Launch}
            label="StackBlitz"
          />
        </span>
      }
      style={{
        width: table.getCenterTotalSize(),
      }}>
      <Table size="lg" useZebraStyles={false} aria-label="sample table">
        <TableHead>
          {table.getHeaderGroups().map((headerGroup) => (
            <TableRow key={headerGroup.id}>
              {headerGroup.headers.map((header) => (
                <TableHeader
                  key={header.id}
                  style={{
                    width: header.getSize(),
                  }}>
                  {header.isPlaceholder
                    ? null
                    : flexRender(
                        header.column.columnDef.header,
                        header.getContext()
                      )}
                </TableHeader>
              ))}
            </TableRow>
          ))}
        </TableHead>
        <TableBody>
          {table.getRowModel().rows.map((row) => (
            <TableRow key={row.id}>
              {row.getVisibleCells().map((cell) => (
                <TableCell
                  key={cell.id}
                  style={{
                    width: cell.column.getSize(),
                  }}>
                  {flexRender(cell.column.columnDef.cell, cell.getContext())}
                </TableCell>
              ))}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
};

// web-components/column-alignment/src/column-alignment.ts
import { LitElement, html, css } from 'lit';
import { customElement } from 'lit/decorators.js';
import { repeat } from 'lit/directives/repeat.js';
import {
  createColumnHelper,
  flexRender,
  getCoreRowModel,
  TableController,
} from '@tanstack/lit-table';
import '@carbon/web-components/es/components/data-table/index.js';
import '@carbon/web-components/es/components/icon-indicator/index.js';
import { ICON_INDICATOR_KIND } from '@carbon/web-components/es/components/icon-indicator/defs.js';

import { makeData, Resource } from './makeData';

const getStatusIconValue = (kind: string): ICON_INDICATOR_KIND => {
  if (kind === 'disabled') {
    return ICON_INDICATOR_KIND.FAILED;
  }
  if (kind === 'starting') {
    return ICON_INDICATOR_KIND['NOT-STARTED'];
  }
  if (kind === 'active') {
    return ICON_INDICATOR_KIND['IN-PROGRESS'];
  }
  return ICON_INDICATOR_KIND['IN-PROGRESS'];
};

const columnHelper = createColumnHelper<Resource>();

const columns = [
  columnHelper.accessor((row) => row.name, {
    id: 'name',
    header: 'Name',
  }),
  columnHelper.accessor('rule', {
    header: 'Rule',
  }),
  columnHelper.accessor('status', {
    header: () => html`<span class="center-align-cell">Status</span>`,
    cell: (info) => {
      return html`<cds-icon-indicator
        class="center-align-cell"
        size="16"
        kind="${getStatusIconValue(info.getValue())}"></cds-icon-indicator> `;
    },
  }),
  columnHelper.accessor('other', {
    header: 'Other',
  }),
  columnHelper.accessor('example', {
    header: () => html`<span class="right-align-cell">Example</span>`,
    cell: (info) =>
      html`<span class="right-align-cell">${info.getValue()}</span>`,
  }),
];

const data: Resource[] = makeData(10);

/**
 * An example table using `@tanstack/lit-table` and `@carbon/web-components` DataTable.
 *
 */

@customElement('column-alignment-tanstack-table')
export class ColumnAlignmentTanstackTable extends LitElement {
  private tableController = new TableController<Resource>(this);

  render() {
    const table = this.tableController.table({
      columns,
      data,
      getCoreRowModel: getCoreRowModel(),
    });

    return html`
      <cds-table>
        <cds-table-head>
          ${repeat(
            table.getHeaderGroups(),
            (headerGroup) => headerGroup.id,
            (headerGroup) =>
              html`<cds-table-header-row>
                ${repeat(
                  headerGroup.headers,
                  (header) => header.id,
                  (header) =>
                    html` <cds-table-header-cell>
                      ${header.isPlaceholder
                        ? null
                        : flexRender(
                            header.column.columnDef.header,
                            header.getContext()
                          )}
                    </cds-table-header-cell>`
                )}</cds-table-header-row
              >`
          )}
        </cds-table-head>
        <cds-table-body>
          ${repeat(
            table.getRowModel().rows,
            (row) => row.id,
            (row) => html`
              <cds-table-row>
                ${repeat(
                  row.getVisibleCells(),
                  (cell) => cell.id,
                  (cell) =>
                    html` <cds-table-cell>
                      ${flexRender(
                        cell.column.columnDef.cell,
                        cell.getContext()
                      )}
                    </cds-table-cell>`
                )}
              </cds-table-row>
            `
          )}
        </cds-table-body>
      </cds-table>
    `;
  }

  static styles = css`
    :host {
      max-width: 1280px;
      margin: 0 auto;
      padding: 2rem;
      display: flex;
      place-items: center;
    }
    .right-align-cell {
      display: block;
      text-align: right;
    }
    .center-align-cell {
      display: block;
      text-align: center;
    }
  `;
}

declare global {
  interface HTMLElementTagNameMap {
    'column-alignment-tanstack-table': ColumnAlignmentTanstackTable;
  }
}
