// web-components/selectable-nested-rows/src/selectableNestedRows.ts
import { LitElement, css, html } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { repeat } from 'lit/directives/repeat.js';
import {
  createColumnHelper,
  flexRender,
  getCoreRowModel,
  getExpandedRowModel,
  TableController,
} from '@tanstack/lit-table';
import '@carbon/web-components/es/components/data-table/index.js';
import '@carbon/web-components/es/components/button/index.js';
import ChevronRight from '@carbon/web-components/es/icons/chevron--right/16';
import { styleMap } from 'lit/directives/style-map.js';

import { makeData, Resource } from './makeData';

const columnHelper = createColumnHelper<Resource>();

const data: Resource[] = makeData(10, 3, 3, 2);

/**
 * An example table using `@tanstack/lit-table` and `@carbon/web-components` DataTable.
 *
 */

@customElement('selectable-nested-rows-table')
export class SelectableNestedRowsTable extends LitElement {
  private tableController = new TableController<Resource>(this);

  _columns = [
    columnHelper.accessor((row) => row.name, {
      id: 'name',
      header: ({ table }) => html` <div class="flex">
        <cds-button
          @click=${table.getToggleAllRowsExpandedHandler()}
          class="row-expander"
          kind="ghost"
          size="sm">
          ${ChevronRight({
            slot: 'icon',
            class: table.getIsAllRowsExpanded()
              ? `row-expanded-icon`
              : 'row-expandable-icon',
          })}
        </cds-button>
        <span>Name</span>
      </div>`,
      cell: ({ row, renderValue }) => {
        return html` <div
          style="${styleMap({
            paddingLeft: `${row.depth * 2 + (!row.getCanExpand() ? 2 : 0)}rem`,
          })}">
          <div class="flex">
            ${row.getCanExpand()
              ? html`<cds-button
                  @click=${row.getToggleExpandedHandler()}
                  class="row-expander"
                  kind="ghost"
                  size="sm">
                  ${ChevronRight({
                    slot: 'icon',
                    class: row.getIsExpanded()
                      ? `row-expanded-icon`
                      : 'row-expandable-icon',
                  })}
                </cds-button>`
              : null}
            ${renderValue()}
          </div>
        </div>`;
      },
    }),
    columnHelper.accessor('rule', {
      header: () => 'Rule',
      cell: (info) => info.renderValue(),
    }),
    columnHelper.accessor('status', {
      header: () => html`<span>Status</span>`,
    }),
    columnHelper.accessor('other', {
      header: 'Other',
    }),
    columnHelper.accessor('example', {
      header: 'Example',
    }),
  ];

  @state()
  private _expanded = {};

  render() {
    const table = this.tableController.table({
      columns: this._columns,
      data,
      getCoreRowModel: getCoreRowModel(),
      getExpandedRowModel: getExpandedRowModel(),
      getSubRows: (row) => row.subRows,
      state: {
        expanded: this._expanded,
      },
      onExpandedChange: (oldExpanded) => {
        this._expanded =
          typeof oldExpanded === 'function'
            ? oldExpanded(this._expanded)
            : oldExpanded;
      },
    });

    return html`
      <cds-table>
        <cds-table-head>
          ${repeat(
            table.getHeaderGroups(),
            (headerGroup) => headerGroup.id,
            (headerGroup) =>
              html`<cds-table-header-row>
                ${repeat(
                  headerGroup.headers,
                  (header) => header.id,
                  (header) =>
                    html` <cds-table-header-cell>
                      ${header.isPlaceholder
                        ? null
                        : flexRender(
                            header.column.columnDef.header,
                            header.getContext()
                          )}
                    </cds-table-header-cell>`
                )}</cds-table-header-row
              >`
          )}
        </cds-table-head>
        <cds-table-body>
          ${repeat(
            table.getRowModel().rows,
            (row) => row.id,
            (row) => html`
              <cds-table-row>
                ${repeat(
                  row.getVisibleCells(),
                  (cell) => cell.id,
                  (cell) =>
                    html` <cds-table-cell>
                      ${flexRender(
                        cell.column.columnDef.cell,
                        cell.getContext()
                      )}
                    </cds-table-cell>`
                )}
              </cds-table-row>
            `
          )}
        </cds-table-body>
      </cds-table>
    `;
  }

  static styles = css`
    :host {
      max-width: 1280px;
      margin: 0 auto;
      padding: 2rem;
      display: flex;
      place-items: center;
    }

    .flex {
      display: flex;
      align-items: center;
    }

    .row-expander {
      margin-right: 1rem;
    }

    .row-expandable-icon {
      color: var(--cds-icon-primary, #161616);
      transition: transform 150ms ease-in;
    }

    .row-expanded-icon {
      color: var(--cds-icon-primary, #161616);
      transform: rotate(0.25turn);
      transition: transform 150ms ease-in; // replace with carbon motion easing
    }
  `;
}

declare global {
  interface HTMLElementTagNameMap {
    'nested-row-table': SelectableNestedRowsTable;
  }
}

// react/selectable-nested-rows/src/Example/SelectableNestedRows.tsx
import React from 'react';

import {
  ExpandedState,
  useReactTable,
  getCoreRowModel,
  getExpandedRowModel,
  ColumnDef,
  flexRender,
} from '@tanstack/react-table';
import { DataTable, TableContainer, Button } from '@carbon/react';
import { ChevronRight } from '@carbon/react/icons';
const { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } =
  DataTable;

import { makeData, Resource } from './makeData';

export const SelectableNestedRows = () => {
  const columns = React.useMemo<ColumnDef<Resource>[]>(
    () => [
      {
        accessorKey: 'name',
        header: ({ table }) => (
          <div className="flex">
            <Button
              {...{
                onClick: table.getToggleAllRowsExpandedHandler(),
              }}
              className="row-expander"
              kind="ghost"
              size="sm">
              {table.getIsAllRowsExpanded() ? (
                <ChevronRight className="row-expanded-icon" />
              ) : (
                <ChevronRight />
              )}
            </Button>
            Name
          </div>
        ),
        cell: ({ row, getValue }) => (
          <div
            style={{
              // Since rows are flattened by default,
              // we can use the row.depth property
              // and paddingLeft to visually indicate the depth
              // of the row
              paddingLeft: `${
                row.depth * 2 + (!row.getCanExpand() ? 2 : 0)
              }rem`,
            }}>
            <div className="flex">
              {row.getCanExpand() ? (
                <Button
                  {...{
                    onClick: row.getToggleExpandedHandler(),
                    style: { cursor: 'pointer' },
                  }}
                  className="row-expander"
                  kind="ghost"
                  size="sm">
                  {row.getIsExpanded() ? (
                    <ChevronRight className="row-expanded-icon" />
                  ) : (
                    <ChevronRight />
                  )}
                </Button>
              ) : null}{' '}
              {getValue<boolean>()}
            </div>
          </div>
        ),
      },
      {
        accessorFn: (row) => row.rule,
        id: 'rule',
        cell: (info) => info.getValue(),
        header: () => <span>Rule</span>,
      },
      {
        accessorKey: 'status',
        header: () => 'Status',
      },
      {
        accessorKey: 'other',
        header: () => <span>Other</span>,
      },
    ],
    []
  );

  const [data] = React.useState(() => makeData(10, 5, 3));

  const [expanded, setExpanded] = React.useState<ExpandedState>({});

  const table = useReactTable({
    data,
    columns,
    state: {
      expanded,
    },
    onExpandedChange: setExpanded,
    getSubRows: (row) => row.subRows,
    getCoreRowModel: getCoreRowModel(),
    getExpandedRowModel: getExpandedRowModel(),
    // filterFromLeafRows: true,
    // maxLeafRowFilterDepth: 0,
    // debugTable: true,
  });

  return (
    <TableContainer title="Selectable nested rows" className="tanstack-example">
      <Table>
        <TableHead>
          {table.getHeaderGroups().map((headerGroup) => (
            <TableRow key={headerGroup.id}>
              {headerGroup.headers.map((header) => {
                return (
                  <TableHeader key={header.id} colSpan={header.colSpan}>
                    {header.isPlaceholder
                      ? null
                      : flexRender(
                          header.column.columnDef.header,
                          header.getContext()
                        )}
                  </TableHeader>
                );
              })}
            </TableRow>
          ))}
        </TableHead>
        <TableBody>
          {table.getRowModel().rows.map((row) => {
            return (
              <TableRow key={row.id}>
                {row.getVisibleCells().map((cell) => {
                  return (
                    <TableCell key={cell.id}>
                      {flexRender(
                        cell.column.columnDef.cell,
                        cell.getContext()
                      )}
                    </TableCell>
                  );
                })}
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
    </TableContainer>
  );
};
