// react/ai-label/src/WithSelection.tsx
import React, { useState } from 'react';
import { Checkbox, DataTable, Pagination, Button } from '@carbon/react';
import { TrashCan, Add, Save, Download } from '@carbon/react/icons';
import cx from 'classnames';
const {
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableHeader,
  TableRow,
  TableToolbar,
  TableBatchActions,
  TableBatchAction,
  TableToolbarContent,
  TableToolbarSearch,
  TableToolbarAction,
  TableToolbarMenu,
} = DataTable;

import {
  createColumnHelper,
  flexRender,
  getCoreRowModel,
  useReactTable,
  FilterFn,
  PaginationState,
  getPaginationRowModel,
  getFilteredRowModel,
} from '@tanstack/react-table';

// A TanStack fork of Kent C. Dodds' match-sorter library that provides ranking information
import { rankItem } from '@tanstack/match-sorter-utils';

import { makeData, type Resource } from './makeData';

// Define a custom fuzzy filter function that will apply ranking info to rows (using match-sorter utils)
const fuzzyFilter: FilterFn<any> = (row, columnId, value, addMeta) => {
  // Rank the item
  const itemRank = rankItem(row.getValue(columnId), value);

  // Store the itemRank info
  addMeta({
    itemRank,
  });

  // Return if the item should be filtered in/out
  return itemRank.passed;
};

export const WithSelection = () => {
  const columnHelper = createColumnHelper<Resource>();

  const [globalFilter, setGlobalFilter] = React.useState('');
  const [rowSelection, setRowSelection] = React.useState({});
  const [data] = useState(makeData(200, { aiLabelRows: [1, 3] }));
  const [pagination, setPagination] = React.useState<PaginationState>({
    pageIndex: 0,
    pageSize: 10,
  });

  const columns = [
    {
      id: 'select',
      width: 48,
      header: ({ table }) => (
        // TableSelectAll throws DOM nesting error, using Checkbox instead to avoid this
        <>
          <Checkbox
            {...{
              checked: table.getIsAllPageRowsSelected(),
              indeterminate: table.getIsSomePageRowsSelected(),
              onChange: () => {
                const isIndeterminate = table.getIsSomeRowsSelected();
                if (!isIndeterminate) {
                  table.toggleAllPageRowsSelected(true);
                }
                if (table.getIsAllPageRowsSelected()) {
                  table.toggleAllRowsSelected(false);
                  return;
                }
                if (isIndeterminate) {
                  table.toggleAllPageRowsSelected(true);
                  return;
                }
              },
              id: 'batch-checkbox',
              labelText: 'header checkbox',
              hideLabel: true,
            }}
          />
        </>
      ),
      cell: ({ row }) => (
        <Checkbox
          {...{
            checked: row.getIsSelected(),
            disabled: !row.getCanSelect(),
            indeterminate: row.getIsSomeSelected(),
            onChange: row.getToggleSelectedHandler(),
            id: `batch-checkbox__${row.id}`,
            labelText: 'row checkbox',
            hideLabel: true,
          }}
        />
      ),
    },
    columnHelper.accessor((row) => row.name, {
      id: 'name',
      cell: (info) => <i>{info.getValue()}</i>,
      header: () => <span>Name</span>,
    }),
    columnHelper.accessor('rule', {
      header: () => 'Rule',
      cell: (info) => info.renderValue(),
    }),
    columnHelper.accessor('status', {
      header: () => <span>Status</span>,
    }),
    columnHelper.accessor('other', {
      header: 'Other',
    }),
    columnHelper.accessor('example', {
      header: 'Example',
    }),
  ];

  const table = useReactTable({
    data,
    columns,
    getCoreRowModel: getCoreRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    onPaginationChange: setPagination,
    getFilteredRowModel: getFilteredRowModel(),
    state: {
      pagination,
      rowSelection,
      globalFilter,
    },
    onGlobalFilterChange: setGlobalFilter,
    globalFilterFn: 'fuzzy', //apply fuzzy filter to the global filter (most common use case for fuzzy filter)
    filterFns: {
      fuzzy: fuzzyFilter, //define as a filter function that can be used in column definitions
    },
    // enableRowSelection: true, //enable row selection for all rows
    enableRowSelection: (row) => row.original.status !== 'disabled', // conditionally disable rows
    // enableRowSelection: row => row.original.age > 18, // or enable row selection
    onRowSelectionChange: setRowSelection,
  });

  const shouldShowBatchActions = Object.keys(rowSelection).length > 0;

  return (
    <TableContainer
      title="AI label, with row selection"
      className="basic-table tanstack-example">
      <TableToolbar aria-label={'Table toolbar'}>
        <TableBatchActions
          shouldShowBatchActions={shouldShowBatchActions}
          totalSelected={Object.keys(rowSelection).length ?? 0}
          onCancel={() => table.resetRowSelection()}
          onSelectAll={() => {
            table.toggleAllRowsSelected(true);
          }}
          totalCount={data?.length}>
          <TableBatchAction
            tabIndex={shouldShowBatchActions ? 0 : -1}
            renderIcon={TrashCan}
            onClick={() => table.resetRowSelection()}>
            Delete
          </TableBatchAction>
          <TableBatchAction
            hasIconOnly
            iconDescription="Add"
            tabIndex={shouldShowBatchActions ? 0 : -1}
            renderIcon={Add}
            onClick={() => table.resetRowSelection()}>
            Delete
          </TableBatchAction>
          <TableBatchAction
            hasIconOnly
            iconDescription="Save"
            tabIndex={shouldShowBatchActions ? 0 : -1}
            renderIcon={Save}
            onClick={() => table.resetRowSelection()}>
            Save
          </TableBatchAction>
          <TableBatchAction
            tabIndex={shouldShowBatchActions ? 0 : -1}
            renderIcon={Download}
            onClick={() => table.resetRowSelection()}>
            Download
          </TableBatchAction>
        </TableBatchActions>
        <TableToolbarContent aria-hidden={shouldShowBatchActions}>
          <TableToolbarSearch
            tabIndex={shouldShowBatchActions ? -1 : 0}
            defaultValue={globalFilter ?? ''}
            onChange={(event: React.ChangeEvent<HTMLInputElement>) =>
              setGlobalFilter(event.target.value)
            }
            placeholder="Search all columns..."
          />
          <TableToolbarMenu tabIndex={shouldShowBatchActions ? -1 : 0}>
            <TableToolbarAction onClick={() => alert('Alert 1')}>
              Action 1
            </TableToolbarAction>
            <TableToolbarAction onClick={() => alert('Alert 2')}>
              Action 2
            </TableToolbarAction>
            <TableToolbarAction onClick={() => alert('Alert 3')}>
              Action 3
            </TableToolbarAction>
          </TableToolbarMenu>
          <Button
            tabIndex={shouldShowBatchActions ? -1 : 0}
            onClick={() => {}}
            kind="primary">
            Add new
          </Button>
        </TableToolbarContent>
      </TableToolbar>
      <Table size="lg" useZebraStyles={false} aria-label="sample table">
        <TableHead>
          {table.getHeaderGroups().map((headerGroup) => (
            <TableRow key={headerGroup.id}>
              {headerGroup.headers.map((header, index) => {
                return (
                  <React.Fragment key={index}>
                    {header.id === 'select' && <TableHeader />}
                    <TableHeader key={header.id} colSpan={header.colSpan}>
                      {header.isPlaceholder
                        ? null
                        : flexRender(
                            header.column.columnDef.header,
                            header.getContext()
                          )}
                    </TableHeader>
                  </React.Fragment>
                );
              })}
            </TableRow>
          ))}
        </TableHead>
        <TableBody>
          {table.getRowModel().rows.map((row) => {
            const aiRow = typeof row.original?.aiLabel === 'function';
            return (
              <TableRow
                key={row.id}
                className={cx([
                  {
                    [`ai-row`]: aiRow,
                  },
                ])}>
                {row.getVisibleCells().map((cell, index) => {
                  const slug = cell.row.original?.aiLabel;
                  const SlugComponent =
                    typeof slug === 'function' ? slug : null;
                  return (
                    <React.Fragment key={index}>
                      {index === 0 && (
                        <TableCell className="ai-cell-select">
                          {SlugComponent && <SlugComponent />}
                        </TableCell>
                      )}
                      <TableCell key={cell.id}>
                        {flexRender(
                          cell.column.columnDef.cell,
                          cell.getContext()
                        )}
                      </TableCell>
                    </React.Fragment>
                  );
                })}
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
      <Pagination
        page={table.getState().pagination.pageIndex + 1}
        totalItems={data.length}
        pagesUnknown={false}
        pageInputDisabled={undefined}
        pageSizeInputDisabled={undefined}
        backwardText={'Previous page'}
        forwardText={'Next page'}
        pageSize={table.getState().pagination.pageSize}
        pageSizes={[10, 20, 30, 40, 50]}
        itemsPerPageText={'Items per page:'}
        onChange={({ pageSize, page }) => {
          table.setPageSize(Number(pageSize));
          table.setPageIndex(page - 1);
        }}
      />
      <p>
        {Object.keys(rowSelection).length} of{' '}
        {table.getPreFilteredRowModel().rows.length} Total Rows Selected
      </p>
    </TableContainer>
  );
};

// web-components/ai-label/src/with-selection.ts
import { LitElement, css, html, unsafeCSS } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { repeat } from 'lit/directives/repeat.js';
import {
  ColumnDef,
  flexRender,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  TableController,
} from '@tanstack/lit-table';
import '@carbon/web-components/es/components/data-table/index.js';
import '@carbon/web-components/es/components/checkbox/index.js';
import '@carbon/web-components/es/components/pagination/index.js';
import '@carbon/web-components/es/components/overflow-menu/index.js';
import Settings from '@carbon/web-components/es/icons/settings/16.js';
import TrashCan from '@carbon/web-components/es/icons/trash-can/16.js';
import Add from '@carbon/web-components/es/icons/add/16.js';
import Save from '@carbon/web-components/es/icons/save/16.js';
import Download from '@carbon/web-components/es/icons/download/16.js';
import { makeData } from './makeData';
import {
  CDSPagination,
  CDSTableToolbarSearch,
} from '@carbon/web-components/es';
import indexStyles from './index.scss?inline';

const styles = css`
  ${unsafeCSS(indexStyles)}
`;

type Resource = {
  id: string;
  name: string;
  rule: string;
  status: string;
  other: string;
  example: string;
};

const columns: ColumnDef<Resource, any>[] = [
  // {
  //   id: 'select',
  //   header: ({ table }) => {
  //     console.log(table.getIsAllRowsSelected());
  //     return html`
  //       <cds-checkbox
  //         ?checked="${table.getIsAllRowsSelected()}"
  //         .indeterminate="${table.getIsSomeRowsSelected()}"
  //         @cds-checkbox-changed="${table.getToggleAllRowsSelectedHandler()}"></cds-checkbox>
  //     `;
  //   },
  //   cell: ({ row }) => html`
  //     <cds-checkbox
  //       @cds-checkbox-changed='${row.getToggleSelectedHandler()}'
  //       ?checked='${row.getIsSelected()}'
  //       ?disabled='${!row.getCanSelect()}'
  //       .indeterminate='${row.getIsSomeSelected()}'
  //     /></cds-checkbox>
  //   `,
  // },
  {
    accessorKey: 'name',
    cell: (info) => info.getValue(),
  },
  {
    accessorFn: (row) => row.rule,
    id: 'rule',
    cell: (info) => info.getValue(),
    header: () => html`<span>Rule</span>`,
  },
  {
    accessorKey: 'status',
    header: () => 'Status',
  },
  {
    accessorKey: 'other',
    header: () => html`<span>Other</span>`,
  },
  {
    accessorKey: 'example',
    header: 'Example',
  },
];

const data: Resource[] = makeData(100, { aiLabelRows: [1, 3] });
console.log(data);

/**
 * An example table using `@tanstack/lit-table` and `@carbon/web-components` DataTable.
 *
 */

@customElement('with-selection-table')
export class MyBatchTable extends LitElement {
  private tableController = new TableController<Resource>(this);

  @state()
  private _rowSelection: Record<string, boolean> = {};

  @state()
  private _globalFilter = '';

  render() {
    const table = this.tableController.table({
      columns,
      data,
      filterFns: {},
      state: {
        rowSelection: this._rowSelection,
        globalFilter: this._globalFilter,
      },
      enableRowSelection: true,
      enableGlobalFilter: true,
      onRowSelectionChange: (updaterOrValue) => {
        if (typeof updaterOrValue === 'function') {
          this._rowSelection = updaterOrValue(this._rowSelection);
        } else {
          this._rowSelection = updaterOrValue;
        }
      },
      getCoreRowModel: getCoreRowModel(),
      getFilteredRowModel: getFilteredRowModel(),
      getPaginationRowModel: getPaginationRowModel(),
      debugTable: true,
    });

    console.log(table.getRowModel().rowsById);

    console.log(table.getState().rowSelection);
    console.log(table.getRowCount());
    console.log('are some rows selected: ', table.getIsSomeRowsSelected());

    interface paginationDetail {
      detail: {
        pageSize: number;
        page: number;
      };
    }
    interface toolbarSearchDetail {
      detail: {
        value: string;
      };
    }
    interface searchFull extends CDSTableToolbarSearch, toolbarSearchDetail {}
    interface paginationFull extends CDSPagination, paginationDetail {}

    return html`
      <cds-table with-row-ai-labels>
        <cds-table-header-title slot="title"
          >AI label, with row selection</cds-table-header-title
        >

        <cds-table-toolbar slot="toolbar">
          <cds-table-batch-actions
            ?active=${table.getIsSomeRowsSelected()}
            selected-rows-count=${table.getSelectedRowModel().rows.length}
            @cds-table-batch-actions-cancel-clicked=${() =>
              table.toggleAllRowsSelected(false)}>
            <cds-button>Delete ${TrashCan({ slot: 'icon' })}</cds-button>
            <cds-button tooltip-position="bottom" tooltip-text="Add"
              >${Add({ slot: 'icon' })}</cds-button
            >
            <cds-button tooltip-position="bottom" tooltip-text="Save"
              >${Save({ slot: 'icon' })}</cds-button
            >
            <cds-button href="javascript:void 0" download="table-data.json">
              Download ${Download({ slot: 'icon' })}
            </cds-button>
          </cds-table-batch-actions>
          <cds-table-toolbar-content>
            <cds-table-toolbar-search
              placeholder="Filter table"
              @cds-search-input=${(e: searchFull) =>
                (this._globalFilter =
                  e.detail.value)}></cds-table-toolbar-search>
            <cds-overflow-menu toolbar-action>
              ${Settings({
                slot: 'icon',
                class: `custom-icon-class`,
              })}
              <cds-overflow-menu-body>
                <cds-overflow-menu-item @click=${() => alert('Alert 1')}>
                  Action 1
                </cds-overflow-menu-item>
                <cds-overflow-menu-item @click=${() => alert('Alert 2')}>
                  Action 2
                </cds-overflow-menu-item>
                <cds-overflow-menu-item @click=${() => alert('Alert 3')}>
                  Action 3
                </cds-overflow-menu-item>
              </cds-overflow-menu-body>
            </cds-overflow-menu>
            <cds-button>Primary button</cds-button>
          </cds-table-toolbar-content>
        </cds-table-toolbar>
        <cds-table-head>
          ${repeat(
            table.getHeaderGroups(),
            (headerGroup) => headerGroup.id,
            (headerGroup) =>
              html`<cds-table-header-row>
                ${repeat(
                  headerGroup.headers,
                  (header) => header.id,
                  (header) =>
                    html` <cds-table-header-cell>
                      ${header.isPlaceholder
                        ? null
                        : flexRender(
                            header.column.columnDef.header,
                            header.getContext()
                          )}
                    </cds-table-header-cell>`
                )}</cds-table-header-row
              >`
          )}
        </cds-table-head>
        <cds-table-body>
          ${repeat(
            table.getRowModel().rows,
            (row) => row.id,
            (row) => {
              return html`
                <cds-table-row selection-name=${row.id}>
                  ${row.original.aiLabel?.({
                    alignment: 'bottom-left',
                  })}
                  ${repeat(
                    row.getVisibleCells(),
                    (cell) => cell.id,
                    (cell) => {
                    console.log(cell)
                      return html` <cds-table-cell>
                        ${flexRender(
                          cell.column.columnDef.cell,
                          cell.getContext()
                        )}
                      </cds-table-cell>`;
                    }
                  )}
                </cds-table-row>
              `;
            }
          )}
        </cds-table-body>
      </cds-table>
      <cds-pagination
        start="0"
        total-items="${table.getRowCount()}"
        @cds-pagination-changed-current="${(event: paginationFull) => {
          const { pageSize, page } = event.detail;
          table.setPageSize(Number(pageSize));
          table.setPageIndex(page - 1);
        }}">
        <cds-select-item value="10">10</cds-select-item>
        <cds-select-item value="20">20</cds-select-item>
        <cds-select-item value="30">30</cds-select-item>
        <cds-select-item value="40">40</cds-select-item>
        <cds-select-item value="50">50</cds-select-item>
      </cds-pagination>
    `;
  }

  static styles = [
    css`
      :host {
        max-width: 1280px;
        margin: 0 auto;
        padding: 2rem;
        display: flex;
        place-items: center;
        flex-direction: column;
      }
      cds-table-batch-actions[active] {
        z-index: 1;
        clip-path: polygon(0 0, 300% 0, 300% 300%, 0 300%);
        opacity: 1;
        pointer-events: all;
        transform: translate3d(0, 0, 0);
      }
    `,
    styles,
  ];
}

declare global {
  interface HTMLElementTagNameMap {
    'with-selection-table': MyBatchTable;
  }
}
